# Generated by Django 4.1.7 on 2023-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_created',
            field=models.DateTimeField(),
        ),
    ]
