# Generated by Django 4.1.7 on 2023-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0002_alter_orders_order_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
