# Generated by Django 4.1.7 on 2023-03-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_ordered',
        ),
        migrations.AddField(
            model_name='customer',
            name='orderes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='POSDemo.orders'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity_type',
            field=models.CharField(choices=[('GM', 'Gram'), ('LT', 'Litre'), ('UNIT', 'Units')], default='UNIT', max_length=10),
        ),
    ]
