# Generated by Django 4.1.7 on 2023-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0006_remove_orders_customer_ordered_customer_orderes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='POSDemo.product'),
        ),
    ]
