# Generated by Django 4.1.7 on 2023-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSDemo', '0009_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_order_price',
            field=models.IntegerField(),
        ),
    ]
